nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'X-Inertia', 'X-Inertia-Version', 'X-Requested-With']
        expose_headers: ['X-Inertia', 'X-Inertia-Location']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/': ~